jobs:
  run:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./action/run

name: Workflow

on:
  schedule:
    - cron: "10 1/3 * * *"
